# Generated by Django 2.0.2 on 2018-03-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='course_registeration',
            field=models.BooleanField(default=True),
        ),
    ]
