# Generated by Django 2.0.2 on 2018-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0002_voterlist_course_registeration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votespg',
            old_name='cbs',
            new_name='pgs_7',
        ),
        migrations.RemoveField(
            model_name='votesug',
            name='cbs',
        ),
        migrations.AlterField(
            model_name='contestants',
            name='post',
            field=models.CharField(choices=[('VP', 'Vice President'), ('HAB', 'Gen Sec - Hostel Affairs Board'), ('TECH', 'Gen Sec - Technical Board'), ('CULT', 'Gen Sec - Cultural Board'), ('WELFARE', 'Gen Sec - Students Welfare Board'), ('SPORTS', 'Gen Sec - Sports Board'), ('SAIL', 'Gen Sec - SAIL'), ('UGS', 'Under Graduate Senator'), ('PGS', 'Post Graduate Senator'), ('GS', 'Girl Senator')], max_length=7),
        ),
    ]
