# Generated by Django 2.0.2 on 2018-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0004_auto_20180318_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='dept',
            field=models.CharField(choices=[('BSBE', 'BSBE'), ('CE', 'CE'), ('CH', 'CH'), ('CL', 'CL'), ('CSE', 'CSE'), ('CST', 'CST'), ('DD', 'DD'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ENC', 'ENC'), ('ENV', 'ENV'), ('EPH', 'EPH'), ('HSS', 'HSS'), ('LST', 'LST'), ('MA', 'MA'), ('MC', 'MC'), ('ME', 'ME'), ('NT', 'NT'), ('PH', 'PH'), ('RT', 'RT'), ('NotListed', 'NotListed')], max_length=100),
        ),
    ]
