# Generated by Django 2.0.2 on 2018-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0005_auto_20180318_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='hostel',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('Married Scholars', 'Married Scholars'), ('NA1', 'NA1')], max_length=100),
        ),
    ]
