# Generated by Django 2.0.2 on 2018-03-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0006_auto_20180318_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlist',
            name='course_registeration',
        ),
    ]
