# Generated by Django 2.0.2 on 2018-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0008_auto_20180318_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='course_registeration',
            field=models.BooleanField(default=True),
        ),
    ]
