# Generated by Django 2.0.2 on 2018-03-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_elections', '0009_voterlist_course_registeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='votespg',
            name='swc',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votesug',
            name='swc',
            field=models.CharField(default='an', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestants',
            name='post',
            field=models.CharField(choices=[('VP', 'Vice President'), ('HAB', 'Gen Sec - Hostel Affairs Board'), ('TECH', 'Gen Sec - Technical Board'), ('CULT', 'Gen Sec - Cultural Board'), ('WELFARE', 'Gen Sec - Students Welfare Board'), ('SPORTS', 'Gen Sec - Sports Board'), ('SAIL', 'Gen Sec - SAIL'), ('SWC', 'Gen Sec - SWC'), ('UGS', 'Under Graduate Senator'), ('PGS', 'Post Graduate Senator'), ('GS', 'Girl Senator')], max_length=7),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='dept',
            field=models.CharField(choices=[('BSBE', 'BSBE'), ('CE', 'CE'), ('CH', 'CH'), ('CL', 'CL'), ('CSE', 'CSE'), ('CST', 'CST'), ('DD', 'DD'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ENC', 'ENC'), ('ENV', 'ENV'), ('EPH', 'EPH'), ('HSS', 'HSS'), ('LST', 'LST'), ('MA', 'MA'), ('MC', 'MC'), ('ME', 'ME'), ('NT', 'NT'), ('PH', 'PH'), ('RT', 'RT'), ('NotListed1', 'NotListed1')], max_length=100),
        ),
    ]
